### ISSUE TITLE
Data Sharing Agreements

### ISSUE THREAD

**Issue by bryangw1** [UMKC-Law/DataSharingAgreement#8]
Location to compile different data sharing agreements

**Comment by dazzaji** [comment]
Perfect.

**Comment by dazzaji** [comment]
What is the Slack channel where we are discussing this?  I want to coordinate a check-in with Chris Osgood and the Code for America fellows working with City of Sommerville ...

**Comment by HazardJ** [comment]
Dazza - do mean a channel on the CommonAccord Slack or is there another one you are referring to. If CommonAccord, I suppose this would be the contracts channel.

**Comment by dazzaji** [comment]
Hi Jim!  I just made a channel on the CodeForKC Slack to try to get those folks involved.  It is called "DataSharingAgreements"...  Do you have or need access there?

**Comment by dazzaji** [comment]
We can do a demo with Chris Osgood and Code for America fellows stationed in Mass from SF on Data Sharing Agreements at 3pm Eastern (in about 40 minutes).  Are you available then, Jim?

**Comment by HazardJ** [comment]
Sure. 

On Jun 6, 2015, at 8:23 PM, Dazza Greenwood notifications@github.com wrote:

> We can do a demo with Chris Osgood and Code for America fellows stationed in Mass from SF on Data Sharing Agreements at 3pm Eastern (in about 40 minutes). Are you available then, Jim?
> 
> —
> Reply to this email directly or view it on GitHub.

James Hazard
33.6.37.47.46.42
@commonaccord

**Comment by ghost** [comment]
NYC - DOT Video & Traffic Flow Data Sharing Agreement
http://www.nyc.gov/html/dot/downloads/pdf/video-partnership-agreement.pdf

**Comment by Merriweather-CH** [comment]
University of Chicago Data Sharing Agreement 
http://researchadmin.uchicago.edu/clinical_trials/DUA%20from%20UCMC.pdf

**Comment by RandyDDunn** [comment]
http://www.cityofchicago.org/city/en/depts/doit/dataset/major_streets.html
City of Chicago Major Streets Data Sharing Agreement

**Comment by RandyDDunn** [comment]
New York Data Sharing Agreement 
http://gis.ny.gov/co-op/agreement.cfm

**Comment by Merriweather-CH** [comment]
City of Houston displays all their 311 info in this Dashboard format 
http://performance.houstontx.gov/311Dashboards#volume

**Comment by RandyDDunn** [comment]
Data Use Agreement regarding HIPPA with University of California San Fransisco Health System
http://hipaa.ucsf.edu/documentation/downloads/DataUseAgreement2007Dec.pdf

**Comment by Merriweather-CH** [comment]
St. Louis University Data Sharing Plan 
www.slu.edu/.../Data_use_agreement_external.doc

**Comment by Merriweather-CH** [comment]
Texas Education Agency Data Sharing Agreement 
http://www.isbe.net/research/data-share/TX-ED-AM1-6a.pdf

**Comment by RandyDDunn** [comment]
HIPPA Data Use Agreement Yale University 
http://hipaa.yale.edu/sites/default/files/files/5039-FR-Data-Use-Agreement.pdf

**Comment by Merriweather-CH** [comment]
Data Sharing Agreement For the State of Washington  

http://www.erdc.wa.gov/data/docs/dataouttemplate.pdf

**Comment by Merriweather-CH** [comment]
Kansas Department of Education Data Sharing Agreement 
http://www.ksde.org/Portals/0/Data%20Media%20Reports/FP%202480%20Data%20Sharing%20Agreement%20with%20Data%20Driven%20Enterprises.pdf

**Comment by Merriweather-CH** [comment]
Florida Agency for Healthcare Administration 
https://www.hcup-us.ahrq.gov/datainnovations/clinicaldata/F8hospitadatasharingagrmt081108.pdf

**Comment by RandyDDunn** [comment]
Privacy Technical Assistance Center FERPA Data Sharing Agreement Checklist
http://ptac.ed.gov/sites/default/files/data-sharing-agreement-checklist.pdf

**Comment by Merriweather-CH** [comment]
Missouri Hwy. Patrol Data Sharing Agreement 
https://www.mshp.dps.missouri.gov/MSHPWeb/PatrolDivisions/CRID/documents/Mo-DExSystemUseAgreementFormSHP-997B.pdf

**Comment by RandyDDunn** [comment]
Data Sharing Agreement Harvard Multi-Regional Clinical Trials http://mrct.globalhealth.harvard.edu/files/mrct/files/dua_template_march_2015.pdf

**Comment by Merriweather-CH** [comment]
State of Louisiana Department of Education 

 https://www.louisianabelieves.com/docs/default-source/data-management/meril---december-2014.pdf?sfvrsn=8

**Comment by dazzaji** [comment]
I'm starting to review the links in comments to this issue #8 and pulling the content out of PDF.  I'll add the extracted pure text files to the repository directly.

**Comment by dazzaji** [comment]
Noticed - there is a broken link to this one: St. Louis University Data Sharing Plan 
www.slu.edu/.../Data_use_agreement_external.doc    Do you have a copy of it?  Or is this an unreviewed link directly from a Google search or something like that?

**Comment by Merriweather-CH** [comment]
Here is the text of that link 

INSTRUCTIONS (delete instructions upon completing the data use agreement): The Data Use Agreement template is to be used for research that exchanges limited PHI with a non-SLU entity.  The PHI being shared/exchanged should qualify as a limited data set. A limited data set may be used for the purpose of research, public health, or health care operations. A limited data set is PHI that excludes direct identifiers of the individual or of relatives, employers, or household members of the individual. 

If your research requires the use of a data use agreement, a copy of the signed agreement (by both parties) should be submitted to the IRB office with other research materials for review.  A copy of the agreement should also be retained by both parties involved in the research as an assurance of this agreement.  

DATA USE AGREEMENT

```
This Data Use Agreement (“Agreement”) is made and entered into as of this ________________ day of ____________, 20__ by and between Saint Louis University d/b/a/ SLUCare, a benevolent corporation located in St. Louis, Missouri (“Covered Entity”), and _____________________________ (“Data Recipient”).
```

WITNESSETH:

```
WHEREAS, Covered Entity may Disclose or make available to Data Recipient, and Data Recipient may Use, Disclose, receive, transmit, maintain or create from, certain information in conjunction with research; and

WHEREAS, Covered Entity and Data Recipient are committed to compliance with the Health Insurance Portability and Accountability Act of 1996 (“HIPAA”) and regulations promulgated thereunder; and

WHEREAS, the purpose of this Agreement is to satisfy the obligations of Covered Entity under HIPAA and to ensure the integrity and confidentiality of certain information Disclosed or make available to Data Recipient and certain information that Data Recipient Uses, Discloses, receives, transmits, maintains or creates, from Covered Entity.

WHEREAS, User agrees to limit its use of the Limited Data Set and protect the Limited Data Set in accordance with the terms of this Agreement and the HIPAA Privacy and Security Rules.

THEREFORE, in consideration of the mutual agreements, terms and conditions herein contained, Covered Entity and User agree as follows:

A.  DEFINITIONS
```

Terns used but not otherwise defined in this Agreement shall have the same meaning as those terms in the Privacy Rule.

```
1.  Individual shall have the same meaning as the term “individual” in 45 CFR Sect. 164.501 of the Privacy Rule and shall include a person who qualifies as a personal representative in accordance with 45 CFR Sect. 164.502(g) of the Privacy Rule.

2.  Limited Data Set shall have the same meaning as the term “limited data set” in 45 CFR 164.514(e) of the Privacy Rule.

3.  Privacy Rule shall mean the Standards for Privacy of Individually Identifiable Information at 45 CFR Part 160 and Part 164, Subparts A and E, as amended from time to time.

4.  Protected Health Information or PHI shall have the same meaning as the term “protected health information” in 45 CFR Sect. 164.501 of the Privacy Rule, to the extent such information is created or received by Data Recipient from Covered Entity.

5.  Required by Law shall have the same meaning as the term “required by law” in 45 CFR Sect. 164.501 of the Privacy Rule.

B.  SCOPE AND PURPOSE

1.  This Agreement sets forth the terms and conditions pursuant to which Covered Entity will Disclose certain PHI to the Data Recipient.
```
1.  Except as otherwise specified herein, Data Recipient may make all Uses and Disclosures of the Limited Data Set necessary to conduct the research described herein: _______________(include a brief description of the research and/or IRB protocol number)¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬_____________________________ (“Research Project”).  
   1.  In addition to the Data Recipient, the individuals, or classes of individuals, who are permitted to Use or receive the Limited Data Set for purposes of the Research Project, include: __________________________________________________________
      _______________________________________________________________________.
   
   C.  OBLIGATIONS AND ACTIVITIES OF DATA RECIPIENT
2.  Data Recipient agrees to not Use or Disclose the Limited Data Set for any purpose other than the Research Project or as Required by Law.
3.  Data Recipient agrees to use appropriate safeguards to prevent Use or Disclosure of the Limited Data Set other than as provided for by this Agreement.
4.  Data Recipient agrees to report to the Covered Entity any Use or Disclosure of the Limited Data Set not provided for by this Agreement of which it becomes aware, including without limitation, any Disclosure of PHI to an unauthorized subcontractor, within ten (10) days of its discovery.
5.  Data Recipient agrees to ensure that any agent, including a subcontractor, to whom it provides the Limited Data Set agrees to the same restrictions and conditions that apply through this Agreement to the Data Recipient with respect to such information.
6.  Data Recipient agrees not to identify the information contained in the Limited Data Set or contact the individual.
7.  Data Recipient will indemnify, defend and hold harmless Covered Entity and any of Covered Entity’s affiliates, and their respective trustees, officers, directors, employees and agents (“Indemnitees”) from and against any claim, cause of action, liability, damage, cost or expense (including, without limitation, reasonable attorney’s fees and court costs) arising out of or in connection with any unauthorized or prohibited Use or Disclosure of the Limited Data Set or any other breach of this Agreement by Data Recipient or any subcontractor, agent or person under Data Recipient’s control.  

D.  TERM AND TERMINATION

Term of this Agreement shall be effective as of the date entered above and shall terminate when all of the Limited Data Set provided by Covered Entity to Data Recipient is destroyed or returned to Covered Entity.  If it is infeasible to return or destroy the Limited Data Set, protections of this Agreement shall extend to such information, in accordance with the termination provisions in Section 2(b).
1.  Upon Covered Entity’s knowledge of a material breach by User, Covered Entity shall have the right to immediately terminate this Agreement.
2.  (a) Except as provided in paragraph (b) of this subsection, upon termination of this Agreement or upon request of Covered Entity, whichever occurs first, User shall return or destroy the Limited Data Set received from Covered Entity.  This provision shall apply to a Limited Data Set that is in the possession of subcontractors or agents of User.  Neither User nor its subcontractors or agents shall retain copies of the Limited Data Set.
   
   ```
   (b) In the event that User determines that returning or destroying the Limited Data Set is not feasible, User shall provide to Covered Entity notification of the conditions that make return or destruction infeasible.  Upon mutual agreement of the Parties that return or destruction of the Limited Data Set is infeasible, User shall extend the protections of this Agreement to such Limited Data Set and limit further uses and disclosures of such Protected Health Information to those purposes that make the return or destruction infeasible, for so long as User maintains such Limited Data Set.
   ```

E.  MISCELLANEOUS
1.  A reference in this Agreement to a section in the Privacy Rule means the section as amended or as renumbered. 
2.  The parties agree to take such action as is necessary to amend this Agreement from time to time as is necessary for Covered Entity to comply with the requirements of the Privacy Rule and HIPAA.  
3.  The respective rights and obligations of Data Recipient under Section C of this Agreement shall survive termination of this Agreement. 
   1.  Any ambiguity in this Agreement shall be resolved to permit Covered Entity to comply with the Privacy Rule.  
4.  There are no intended third party beneficiaries to this Agreement.  Without in any way limiting the foregoing, it is the parties’ specific intent that nothing contained in this Agreement gives rise to any right or cause of action, contractual or otherwise, in or on behalf of the individuals whose PHI is Used or Disclosed pursuant to this Agreement.   
   1.  No provision of this Agreement may be waived except by an agreement in writing signed by the waiving party.  A waiver of any term or provision shall not be construed as a waiver of any other term or provision.    
   2.  The persons signing below have the right and authority to execute this Agreement and no further approvals are necessary to create a binding agreement. 
5.  In the event of any conflict between the terms and conditions stated within this Agreement and those contained within any other agreement or understanding between the parties, written, oral or implied, the terms of this Agreement shall govern.  Without limiting the foregoing, no provision of any other agreement or understanding between the parties limiting the liability of Data Recipient to Covered Entity shall apply to the breach of any covenant in this Agreement by Data Recipient.   
   1.  This Agreement shall be construed in accordance with and governed by the laws of the State of Missouri. 

IN WITNESS WHEREOF, the parties have executed this Agreement effective upon the Effective Date set forth above. 

COVERED ENTITY:             DATA RECIPIENT:

SAINT LOUIS UNIVERSITY          

```
                        ______________________________
```

Name:                           Name:                   

Title:                          Title:

**Comment by dazzaji** [comment]
Thanks. Glad to see this in pure text format. O

**Comment by HazardJ** [comment]
Yes!  It is very clean.  See Slack channel for the steps in taking this from text to Cmacc. Here is where the current version will be displayed: http://datashare-commonaccord.herokuapp.com/index.php?action=source&file=/H4KC/Form/Master_DSA.md.

**Comment by bryangw1** [comment]
Inter-Agency DSA: http://www.ncwd-youth.info/assets/guides/assessment/sample_forms/data_share.pdf

**Comment by HazardJ** [comment]
It's great to see all these precedents being accumulated!  As you do this, you might keep track of the top level headings of the documents.  These will be the basis of organizing a master document and form a rough index of the subject matter.  E.g. like http://my.commonaccord.org/index.php?action=source&file=/NDA/Form/NDA_Form.md

**Comment by bryangw1** [comment]
I think our tentative plan is to begin populating the clause bank folder with different clauses (FERPA, HIPPA) that might be triggered by system rules once those are written. The way the clause bank folder is set up is in a way that indexes everything a lot better. Our team is meeting tomorrow for a few hours to begin populating the clause bank with what we have in the top-level doc, and then with FERPA/HIPAA clauses.

**Comment by HazardJ** [comment]
Great!  Eager to see your work.

**Comment by bryangw1** [comment]
http://www.co.berks.pa.us/Dept/Planning/Documents/GIS/berks_gis_sharing_agreement.pdf
Berks County, PA - Internal GIS Data Sharing Agreement

**Comment by dazzaji** [comment]
are all of these captured in standard content forms in the repository or wiki etc?  Can you link to them if so and then close this issue?

**Comment by bryangw1** [comment]
Ya. Will do, I was using this as a place to refer back to, when I should have just been compiling them in either the repo in a standardized manner, or in the wiki.

This is the last link I'll post in here:
http://research.med.umich.edu/honest-broker-office/data-sharing-agreements

University of Michigan set of Agreements
DSA: Limited Protected Health Information Dataset
DSA: De-identified Dataset
DSA: Full Protected Health Information Dataset
